config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  get 'home/about' => 'homes#about', as: 'about'



  root 'homes#index'

  resources :books

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index,:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource.id)
	end

	def after_sign_up_path_for(resource)
		user_path(resource.id)
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  before_action :user_check, only:[:edit, :update]

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
    @newbook = Book.new
  	@book = Book.find(params[:id])
  end

  def new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  		flash[:notice] = "You have creatad book successfully."
  		redirect_to book_path(@book.id)
  	else
  		@books = Book.all
  		render action: :index
  	end
  end

  def edit
  end

  def update
  	if @book.update(book_params)
  		flash[:notice] = "You have updated book successfully."
  		redirect_to book_path(@book.id)
  	else
  		@books = Book.all
  		render action: :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
    def book_params
  	  params.require(:book).permit(:title, :body)
    end

    def user_check
        @book = Book.find(params[:id])
    if @book.user != current_user
        redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  before_action :user_check, only:[:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  end

  def index
  	@users = User.all
  	@book = Book.new
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:notice] = "You have updated user successfully."
  		redirect_to user_path(@user)
  	else
  		@users = User.all
  		render action: :edit
  	end
  end

  private
    def user_params
        params.require(:user).permit(:profile_image, :name, :introduction)
    end

    def user_check
    	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to user_path(current_user)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="top-message col-md-offset-3 col-md-3">

		<h1>Editing Book</h1>
		<!-- form_for部分 -->
		<%= form_for(@book) do |f| %>

			<% if @book.errors.any? %>
				<div id="error_explanation">
					<h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
					<ul>
					<% @book.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
					</ul>
				</div>
			<%end %>

			<h4>Title</h4>
			<%= f.text_field :title %>
			<h4>Opinion</h4>
			<%= f.text_area :body %>
			<div>
				<%= f.submit 'Update Book' %>
			</div>
			<div>
				<%= link_to "Show", book_path(@book) %>
				<%= link_to "Back", books_path %>
			</div>
		<% end %>


</div>

app/views/books/index.html.erb
<!-- %= @user.name % -->
<div class="container">
		<div class="col-xs-3">
			<%= render 'users/userinfo', user: current_user, book: @book %>
		</div>

		<div class="col-xs-9">
		<h1>Books</h1>

		<table  class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th class="title">Title</th>
					<th class="body">Opinion</th>
				</tr>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
						  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', size: '40x40', class: "pull-left profile-img", fallback: "no_image.jpg" %>
						<% end %>
					</td>
					<td>
						<%= link_to book_path(book) do %>
						  <span><%= book.title %></span>
						<% end %>
					</td>
					<td>
						<span><%= book.body %></span>
					</td>
				</tr>
				<% end %>
			</thead>
		</table>

</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
		<div class="col-xs-3">
			<%= render 'users/userinfo', user: @book.user, book: @newbook %>
		</div>

		<div class="col-xs-9">
			<h1>Book detail</h1>

			<table class="table table-hover table-inverse">
				<tbody>
					<tr>
						<td>
						  <%= link_to user_path(@book.user) do %>
						    <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', size: '40x40', class: "pull-left profile-img", fallback: "no_image.jpg" %><br>
						    <%= @book.user.name %>
						  <% end %>
						<td>
						<td>
						  <%= link_to book_path(@book) do %>
							  <%= @book.title %>
						  <% end %>
					    </td>

						<td>
						  <p><%= @book.body %></p>
						</td>

						<td>
							<% if @book.user == current_user %>
							  <%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success edit_book_15186" %>
							<% end %>
						</td>
						<td>
							<% if @book.user == current_user %>
							  <%= link_to "Destroy", book_path(@book), class:"btn-sm btn-danger destroy_book_15186", method: :delete, "data-confirm" => "Are you sure?" %>
							<% end %>
						</td>
					</tr>
		</div>
</div>

app/views/homes/about.html.erb
<div class="container">
	<h1>Welcome to <span class="glyphicon glyphicon-book">Bookers!</span></h1>
</div>

app/views/homes/index.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>

<div class="body homes">
	<div class="container">
	<p id="notice"></p>
		<div class="row">
			<div class="top-message col-md-offset-3 col-md-6">
				<h1>
					welcome to <span class="glyphicon glyphicon-book">Bookers !!</span>
				</h1>
				<P>
					In <span class="glyphicon glyphicon-book">Bookers,</span>
				</P>
				<p>
					you can share and exchange your opinions , inpressions , and emotions
				</p>
				<p>
					about varioius books!
				</p>
				<p>
					<%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
				</p>
				<p>
					<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers200</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", current_user, class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %>
              </li>
              <li>
                <%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
              </li>
            <% else %>
              <li>
                <%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to " About", about_path, class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_userinfo.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>

<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', size: '100x100', class: "pull-left profile-img", fallback: "no_image.jpg" %>

<table class="table">
	<tbody>
		<tr>
			<td>name</td>
			<td><%= user.name %></td>
		</tr>
		<tr>
			<td>introduction</td>
			<td><%= user.introduction %></td>
		</tr>
	</tbody>
</table>

	<%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
<%= form_for(book) do |f| %>

	<% if book.errors.any? %>
		<div id="error_explanation">
			<h2><%= book.errors.count %> errors prohibited this book from being saved:</h2>
			<ul>
			<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<%end %>

<div class="field row">
	<h4>Title</h4>
	<%= f.text_field :title %>
</div>

<div class="field row">
	<h4>Opinion</h4>
	<%= f.text_area :body %>
</div>
<div class="field row">
	<div>
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
</div>

<% end %>

app/views/users/edit.html.erb
  <div class="container">
    <div class="col-xs-3">
      <h2>User info</h2>
      <!-- ここにform_forを追加します -->
      <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <%end %>

      <div class=>
        <label class=>Name</label>
        <%= f.text_field :name, autofocus: true, class: "form-control",  placeholder:"名前"%>
      </div>
      <div>
        <label class=>Image</label>
      </div>
      <div>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
      </div>
      <div>
        <label class=>Introduction</label>
        <%= f.text_area :introduction, class: "form-control"%>
      </div>
      <div>
        <%= f.submit "Update User" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container">
		<div class="col-xs-3">
			<%= render 'users/userinfo', user: current_user, book: @book %>
		</div>

		<div class="col-xs-9">
			<h1>Users</h1>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th class="image">image</th>
						<th class="name">name</th>
						<th></th>
					</tr>

					<% @users.all.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', size: '40x40', class: "pull-left profile-img", fallback: "no_image.jpg" %></td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
					</tr>
					<% end %>

				</thead>
			</table>
		</div>

</div>

app/views/users/show.html.erb
<div class="container">
		<div class="col-xs-3">
			<%= render 'users/userinfo', user: @user, book: @book %>
		</div>

		<div class="col-xs-9">
			<h1>Books</h1>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th class="image"></th>
						<th class="title">Title</th>
						<th class="body">Opinion</th>
					</tr>
				</thead>
				<tbody>

					<% @user.books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
							  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', size: '50x50', class: "pull-left profile-img", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td>
							<%= link_to book_path(book) do %>
							  <span><%= book.title %></span>
							<% end %>
						</td>
						<td>
							<span><%= book.body %></span>
						</td>
					</tr>
					<% end %>

				</tbody>
			</table>
		</div>
</div>